import type { Postmortem } from "../types";
import { Card, CardHeader } from "./Card";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <div className="mb-1.5 text-xs font-semibold uppercase tracking-wide text-slate-500">{title}</div>
      {children}
    </div>
  );
}

function BulletList({ items }: { items: string[] }) {
  if (items.length === 0) return <span className="text-sm text-slate-500">none</span>;
  return (
    <ul className="ml-4 list-disc space-y-1 text-sm text-slate-300">
      {items.map((item, i) => (
        <li key={i}>{item}</li>
      ))}
    </ul>
  );
}

export function PostmortemView({ postmortem }: { postmortem: Postmortem }) {
  return (
    <Card className="bg-gradient-to-br from-indigo-500/[0.06] to-transparent">
      <CardHeader title="Postmortem" subtitle="Generated by the Postmortem agent" />
      <div className="space-y-5">
        <Section title="Executive Summary">
          <p className="text-sm text-slate-200">{postmortem.executive_summary}</p>
        </Section>
        <div className="grid gap-5 sm:grid-cols-2">
          <Section title="Root Cause">
            <p className="text-sm text-slate-300">{postmortem.root_cause}</p>
          </Section>
          <Section title="Impact">
            <p className="text-sm text-slate-300">{postmortem.impact}</p>
          </Section>
        </div>
        <Section title="Fix Applied">
          <p className="text-sm text-slate-300">{postmortem.fix_applied}</p>
        </Section>
        <Section title="Timeline">
          <ol className="space-y-1.5 border-l border-white/10 pl-4 text-sm text-slate-300">
            {postmortem.timeline.map((entry, i) => (
              <li key={i} className="relative before:absolute before:-left-[19px] before:top-1.5 before:h-1.5 before:w-1.5 before:rounded-full before:bg-indigo-400">
                {entry}
              </li>
            ))}
          </ol>
        </Section>
        <div className="grid gap-5 sm:grid-cols-2">
          <Section title="Preventive Actions">
            <BulletList items={postmortem.preventive_actions} />
          </Section>
          <Section title="Lessons Learned">
            <BulletList items={postmortem.lessons_learned} />
          </Section>
        </div>
      </div>
    </Card>
  );
}
